<a href="https://colab.research.google.com/github/naymalabonna/CSc44800/blob/main/Assignment%204/JudgingFlowers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
# Imports and pip installations (if needed)
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

# Part 1: Load the dataset

In [36]:
# Load the dataset (load remotely, not locally)
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df["target"] = iris.target

In [37]:
# Output the first 15 rows of the data
df.head(15)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4.8               3.4                1.6               0.2   
12                4.8               3.0                1.4               0.1   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
5        0  
6        0  
7        0  
8        0  
9        0  
10       0  
11       0  
12       0  
13       0  
14       0

In [38]:
# Display a summary of the table information (number of datapoints, etc.)
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?
<br> <br>
The data set contains information about the recorded attributes of three species Iris plants. These recorded attributes are the features, which are: sepal length (cm),	sepal width (cm),	petal length (cm),	and petal width (cm). The labels are the species of flowers and are mapped to the classes based on their corresponding "target" value, which ranges from 0 - 2. 0 maps to the first class setosa, 1 maps to the second class versicolor, and 2 maps to the third class virginica.

# Part 2: Split the dataset into train and test

In [95]:
# Take the dataset and split it into our features (X) and label (y)
X = df[iris.feature_names] 
y = df['target']
# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=100)

# Part 3: Logistic Regression

In [96]:
# i. Use sklearn to train a LogisticRegression model on the training set
logreg_model = LogisticRegression(max_iter=200).fit(X_train.values, y_train.values)

In [97]:
# ii. For a sample datapoint, predict the probabilities for each possible class
logreg_sample = np.array([[5.1, 3.5, 1.4, 0.2]])
logreg_predict = logreg_model.predict_proba(logreg_sample)[0]
print("Class 1 Target 0 - Iris-Setosa: ", logreg_predict[0], "\nClass 2 Target 1 - Iris-Versicolour: ", logreg_predict[1], "\nClass 3 Target 2 - Iris-Virginica: ", logreg_predict[2])

Class 1 Target 0 - Iris-Setosa:  0.9787152794833734 
Class 2 Target 1 - Iris-Versicolour:  0.021284699056788956 
Class 3 Target 2 - Iris-Virginica:  2.145983757981414e-08


In [98]:
# iii. Report on the score for Logistic regression model, what does the score measure?
print("Score: ", logreg_model.score(X_test.values, y_test.values))

Score:  1.0


The score measures the proportion of the variation in the dependent variable that is predictable from the independent variables. The highest score a model can get is 1.0, which means that the model fits the data perfectly. Since the model got a score of 1.0 on the test data, this means that the model makes perfect predictions. 

In [50]:
# iv. Extract the coefficents and intercepts for the boundary line(s)
print("Coefficients:\n ", logreg_model.coef_)
print("Intercepts:\n ", logreg_model.intercept_)

Coefficients:
  [[-0.4157426   0.94190559 -2.46756305 -1.06070547]
 [ 0.55918461 -0.33372017 -0.22916143 -0.87703755]
 [-0.14344201 -0.60818542  2.69672448  1.93774301]]
Intercepts:
  [  9.64495391   2.13876709 -11.78372101]


# Part 4: Support Vector Machine

In [63]:
# i. Use sklearn to train a Support Vector Classifier on the training set
svm_model = SVC(probability=True, random_state=100).fit(X_train.values, y_train.values)

In [59]:
# ii. For a sample datapoint, predict the probabilities for each possible class
svm_sample = np.array([[5.1, 3.5, 1.4, 0.2]])
svm_predict = svm_model.predict_proba(svm_sample)[0]
print("Class 1 Target 0 - Iris-Setosa: ", svm_predict[0], "\nClass 2 Target 1 - Iris-Versicolour: ", svm_predict[1], "\nClass 3 Target 2 - Iris-Virginica: ", svm_predict[2])

Class 1 Target 0 - Iris-Setosa:  0.9747724469297749 
Class 2 Target 1 - Iris-Versicolour:  0.016266760198659396 
Class 3 Target 2 - Iris-Virginica:  0.008960792871565771


In [66]:
# iii. Report on the score for the SVM, what does the score measure?
print("Score: ", svm_model.score(X_test.values, y_test.values))

Score:  1.0


Since the Support Vector Classifier model got a score of 1.0 on the test data, this means that the model fits the data perfectly and makes perfect predictions.

# Part 5: Neural Network

In [74]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set
mlp_model = MLPClassifier(max_iter=1000, random_state=100).fit(X_train.values, y_train.values)

In [75]:
# ii. For a sample datapoint, predict the probabilities for each possible class
mlp_sample = np.array([[5.1, 3.5, 1.4, 0.2]])
mlp_predict = mlp_model.predict_proba(mlp_sample)[0]
print("Class 1 Target 0 - Iris-Setosa: ", mlp_predict[0], "\nClass 2 Target 1 - Iris-Versicolour: ", mlp_predict[1], "\nClass 3 Target 2 - Iris-Virginica: ", mlp_predict[2])

Class 1 Target 0 - Iris-Setosa:  0.9985919476732137 
Class 2 Target 1 - Iris-Versicolour:  0.0014080523248036867 
Class 3 Target 2 - Iris-Virginica:  1.9824630668272114e-12


In [77]:
# iii. Report on the score for the Neural Network, what does the score measure?
print("Score: ", mlp_model.score(X_test.values, y_test.values))

Score:  1.0


Since the Neural Network model also got a score of 1.0 on the test data, this means that the model fits the data perfectly and makes perfect predictions.

In [78]:
# iv: Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)

The highest score achieved by the neural network was 1.0 which was attained by using a max_iter value of 1000 so that a convergence can occur within the iterations and a random_state of 100. 

# Part 6: K-Nearest Neighbors

In [79]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
knn_model = KNeighborsClassifier().fit(X_train.values, y_train.values)

In [83]:
# ii. For a sample datapoint, predict the probabilities for each possible class
knn_sample = np.array([[5.1, 3.5, 1.4, 0.2]])
knn_predict = knn_model.predict_proba(knn_sample)[0]
print("Class 1 Target 0 - Iris-Setosa: ", knn_predict[0], "\nClass 2 Target 1 - Iris-Versicolour: ", knn_predict[1], "\nClass 3 Target 2 - Iris-Virginica: ", knn_predict[2])

Class 1 Target 0 - Iris-Setosa:  1.0 
Class 2 Target 1 - Iris-Versicolour:  0.0 
Class 3 Target 2 - Iris-Virginica:  0.0


In [81]:
# iii. Report on the score for kNN, what does the score measure?
print("Score: ", knn_model.score(X_test.values, y_test.values))

Score:  1.0


Since the k-Neighbors Classifier model also got a score of 1.0 on the test data, this means that the model fits the data perfectly and makes perfect predictions.

# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?
<br><br>
All the models had the same performance on the dataset with a test score of 1.0, which was surprising. This may be because the dataset is too small, a larger dataset might have provided more variance in scores throughout the model. However, when predicting probabilities of the sample datapoint, the KNN model is the only one to predict the correct classifier with perfect accuracy, which may be due to the fact that KNNs are nonparametric models meaning that its structure is determined by the dataset. 
